### ISSUE TITLE
undefined method `shell_out!' for Opennms::Upgrade:Module

### ISSUE THREAD

**Issue by syndesis** [dschlenk/opennms-cookbook#40]
Attempted to do an upgrade and got this error:

```
Recipe: opennms::packages
  * ruby_block[stop opennms before upgrade] action run

    ================================================================================
    Error executing action `run` on resource 'ruby_block[stop opennms before upgrade]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `shell_out!' for Opennms::Upgrade:Module

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/opennms/libraries/upgrade.rb:44:in `upgrade?'
    /var/chef/cache/cookbooks/opennms/recipes/packages.rb:39:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/opennms/recipes/packages.rb

     35: ruby_block 'stop opennms before upgrade' do
     36:   block do
     37:     Opennms::Upgrade.stop_opennms(node)
     38:   end
     39:   only_if { node['opennms']['upgrade'] && Opennms::Upgrade.upgrade?(node) }
     40: end
     41:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/opennms/recipes/packages.rb:35:in `from_file'

    ruby_block("stop opennms before upgrade") do
      action [:run]
      default_guard_interpreter :default
      declared_type :ruby_block
      cookbook_name "opennms"
      recipe_name "packages"
      block #<Proc:0x00000000042c2988@/var/chef/cache/cookbooks/opennms/recipes/packages.rb:36>
      only_if { #code block }
    end

    System Info:
    ------------
    chef_version=14.3.37
    platform=centos
    platform_version=7.4.1708
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

**Comment by dschlenk** [comment]
@syndesis can you provide your run list and any environment/role node attribute settings? So far I'm not able to reproduce this error.

**Comment by syndesis** [comment]
Here's my recipe:
```
include_recipe 'build-essential::default'
include_recipe 'opennms::default'

opennms_snmp_config_definition 'remove_public' do
        read_community 'public'
        version 'v2c'
        action :delete
end

opennms_snmp_config_definition 'snmp_config' do
        read_community 'foobar'
        version 'v2c'
        action :create
        notifies :run, 'opennms_send_event[activate_snmp-config.xml]'
end
```

attributes/default.rb:
```
default[:opennms][:conf][:heap_size] = 1024
default[:opennms][:conf][:addl_mgr_opts] = '-XX:+UseConcMarkSweepGC -XX:MaxMetaspaceSize=512m'
default['opennms']['version'] = '22.0.3-1'
default['opennms']['upgrade'] = true
default['java']['jdk_version'] = '8'
default['java']['install_flavor'] = 'oracle'
default['java']['jdk']['7']['x86_64']['url'] = 'http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz'
default['java']['jdk']['7']['x86_64']['checksum'] = '1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3'
default['java']['oracle']['accept_oracle_download_terms'] = true
```
